# Generated by Django 6.1 on 2026-08-16 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gratitudeentry',
            name='mood',
            field=models.CharField(default='😊', max_length=10),
        ),
    ]
